/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz_pelu;

import java.sql.SQLException;

/**
 *
 * @author Carlos
 */
public class Gestion extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Gestion.class.getName());
    // Se declara el objeto Datos
    private static Datos d;
    // Se declara el objeto Consultas
    private static Consultas c;
    // Se declara el objeto Servicios
    private static Servicios s;
    // Se declara el objeto Index
    private static Index i;
    // Se declara el objeto Simulacion
    private static Simulacion sim;

    /**
     * Creates new form gestion
     */
    public Gestion() {
        System.out.println("Se inicia el objeto gestion");
        initComponents(); // Inicializa los componentes visuales de la interfaz
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        consultas_Btn = new javax.swing.JButton();
        servicios_Btn = new javax.swing.JButton();
        sincro_Btn = new javax.swing.JButton();
        datos_Btn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 0, 102));

        consultas_Btn.setBackground(new java.awt.Color(153, 204, 255));
        consultas_Btn.setFont(new java.awt.Font("Segoe UI Black", 2, 36)); // NOI18N
        consultas_Btn.setText("C O N S U L T A S");
        consultas_Btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        consultas_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultas_BtnActionPerformed(evt);
            }
        });

        servicios_Btn.setBackground(new java.awt.Color(153, 204, 255));
        servicios_Btn.setFont(new java.awt.Font("Segoe UI Black", 2, 36)); // NOI18N
        servicios_Btn.setText("S E R V I C I O S");
        servicios_Btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        servicios_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicios_BtnActionPerformed(evt);
            }
        });

        sincro_Btn.setBackground(new java.awt.Color(153, 204, 255));
        sincro_Btn.setFont(new java.awt.Font("Segoe UI Black", 2, 36)); // NOI18N
        sincro_Btn.setText("S I N C R O N I Z A R");
        sincro_Btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sincro_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sincro_BtnActionPerformed(evt);
            }
        });

        datos_Btn.setBackground(new java.awt.Color(153, 204, 255));
        datos_Btn.setFont(new java.awt.Font("Segoe UI Black", 2, 36)); // NOI18N
        datos_Btn.setText("D A T O S");
        datos_Btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        datos_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datos_BtnActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(153, 204, 255));
        backBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz_pelu/imagenes/BACK (1).png"))); // NOI18N
        backBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        homeBtn.setBackground(new java.awt.Color(153, 204, 255));
        homeBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz_pelu/imagenes/sim__1_-removebg-preview.png"))); // NOI18N
        homeBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datos_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(servicios_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sincro_Btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultas_Btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datos_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultas_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(servicios_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sincro_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    // Accion que hace el boton de consultas
    private void consultas_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultas_BtnActionPerformed
        // TODO add your handling code here:
        System.out.println("funciona el boton consultas");
        // Se cierra la pestaña actual
        this.dispose();
        // Se llama al metodo abrirConsultas para abrir la pantalla de consultas
        c.abrirConsultas();
    }//GEN-LAST:event_consultas_BtnActionPerformed
    // Accion que hace el boton de servicios
    private void servicios_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicios_BtnActionPerformed
        // TODO add your handling code here:
        System.out.println("funciona el boton servicios");
        // Se cierra la pestaña actual
        this.dispose();
        try {
            // Se llama al metodo abrirServicios para abrir la pantalla de servicios
            s.abrirServicios();
        } catch (SQLException ex) {
            // En caso de error de SQL, se registra en el log
            System.getLogger(Gestion.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_servicios_BtnActionPerformed
// Accion que hace el boton de sincronizar 
    private void sincro_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sincro_BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sincro_BtnActionPerformed
// Accion que hace el boton de datos
    private void datos_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datos_BtnActionPerformed
        // TODO add your handling code here:
        System.out.println("funciona el boton datos");
        // Se cierra la pestaña actual
        this.dispose();
        try {
            d.abrirDatos();
            // Se llama al metodo abrirDatos para abrir la pantalla de datos
        } catch (SQLException ex) {
            // En caso de error de SQL, se registra en el log
            System.getLogger(Gestion.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_datos_BtnActionPerformed
// Accion que hace el boton de atras (Vuelve a Index)
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // Se cierra la pestaña actual
        this.dispose();
        // Se llama al metodo abrirIndex para volver a la pantalla principal
        i.abrirIndex();
    }//GEN-LAST:event_backBtnActionPerformed
// Accion que hace el boton de home (Redirige a Simulación)
    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
        // Se cierra la pestaña actual
        this.dispose();
        // Se llama al metodo abrirSimulacion para abrir la pantalla de simulación
        sim.abrirSimulacion();


    }//GEN-LAST:event_homeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public void abrirGestion() throws SQLException {
        // Muestra esta pestaña
        this.setVisible(true);
        
        // Se crean los objetos de las otras pantallas para permitir la navegación
        System.out.println("se crea el objeto datos");
        d = new Datos(); // Crea el objeto Datos
        c = new Consultas(); // Crea el objeto Consultas
        s = new Servicios(); // Crea el objeto Servicios
        i = new Index(); // Crea el objeto Index
        sim = new Simulacion(); // Crea el objeto Simulacion
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton consultas_Btn;
    private javax.swing.JButton datos_Btn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton servicios_Btn;
    private javax.swing.JButton sincro_Btn;
    // End of variables declaration//GEN-END:variables
}
