/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz_pelu;

/**
 *
 * @author Carlos
 */
public class Login extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());
    //Se declara la variable log que se utiliza para determinar si es administrador o empleado
    private static int log;
    //Se declara el objeto Index
    private static Index i;

    //Metodo get de la variable log
    public static int getLog() {
        //devuelve el valor de la variable log
        return log;
    }

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tipoUsu = new javax.swing.JComboBox<>();
        iniSes = new javax.swing.JLabel();
        labelUsu = new javax.swing.JLabel();
        labelContra = new javax.swing.JLabel();
        textContra = new javax.swing.JPasswordField();
        borrarBtn = new javax.swing.JButton();
        iniciarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        tipoUsu.setBackground(new java.awt.Color(204, 0, 102));
        tipoUsu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tipoUsu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Empleado" }));
        tipoUsu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        iniSes.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        iniSes.setText("INICIA SESIÓN");

        labelUsu.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        labelUsu.setText("USUARIO:");

        labelContra.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        labelContra.setText("CONTRASEÑA:");

        textContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textContraActionPerformed(evt);
            }
        });

        borrarBtn.setBackground(new java.awt.Color(204, 0, 102));
        borrarBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        borrarBtn.setText("BORRAR");
        borrarBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        borrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarBtnActionPerformed(evt);
            }
        });

        iniciarBtn.setBackground(new java.awt.Color(204, 0, 102));
        iniciarBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        iniciarBtn.setText("INICIAR");
        iniciarBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        iniciarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(iniSes)
                .addContainerGap(135, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(borrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(iniciarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelContra)
                    .addComponent(labelUsu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textContra, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(iniSes, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsu)
                    .addComponent(tipoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textContra, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelContra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iniciarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Acción del boton iniciar
    private void iniciarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarBtnActionPerformed
        // TODO add your handling code here:
        //En caso de seleccionar administrador y la contraseña ser "1234", realizará el login de administrador
        if (tipoUsu.getSelectedItem() == "Administrador" && "1234".equals(textContra.getText())) {
            log = 0; // Asigna 0 para indicar que es administrador
            
            // Muestra un mensaje de bienvenida
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Bienvenido Admin",
                    "Bienvenido",
                    javax.swing.JOptionPane.PLAIN_MESSAGE);
            
            this.dispose(); // Cierra la pestaña actual (Login)
            
            //Se crea el objeto Index
            i = new Index();
            //Se llama al metodo abrirIndex para abrir la pestaña del Index
            i.abrirIndex();
            
            
            //En caso de seleccionar empleado y la contraseña ser "1234", realizará el login de empleado
        } else if (tipoUsu.getSelectedItem() == "Empleado" && "1234".equals(textContra.getText())) {
            log = 1; // Asigna 1 para indicar que es empleado
            
            // Muestra un mensaje de bienvenida
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Bienvenido empleado",
                    "Bienvenido",
                    javax.swing.JOptionPane.PLAIN_MESSAGE);
            
            this.dispose(); // Cierra la pestaña actual (Login)
            
            //Se crea el objeto Index
            i = new Index();
            //Se llama al metodo abrirIndex para abrir la pestaña del Index
            i.abrirIndex();
            
            
        } else {
            // Si las credenciales no coinciden con ninguna de las opciones
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Contraseña incorrecta",
                    "Error de login",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_iniciarBtnActionPerformed
// Acción del boton borrar: limpia el campo de contraseña
    private void borrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarBtnActionPerformed
        // TODO add your handling code here:
        // Establece el texto del campo de contraseña a vacío
        textContra.setText("");
    }//GEN-LAST:event_borrarBtnActionPerformed

    private void textContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textContraActionPerformed

    /**
     * @param args the command line arguments
     */
    //Metodo que abre el login
    public void abrirLogin() {
        //abre esta pestaña
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarBtn;
    private javax.swing.JLabel iniSes;
    private javax.swing.JButton iniciarBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelContra;
    private javax.swing.JLabel labelUsu;
    private javax.swing.JPasswordField textContra;
    private javax.swing.JComboBox<String> tipoUsu;
    // End of variables declaration//GEN-END:variables
}
