/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz_pelu;

import ConectorBD.Conexion;
import java.sql.SQLException;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alumno
 */
public class Servicios extends javax.swing.JFrame {

    // Declaración del logger (rastreador de la clase)
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Servicios.class.getName());
    // Se declara el objeto Conexion (para obtener los datos de la BD)
    private static Conexion cx;
    // Se declara el objeto Index (para ir a la pantalla principal)
    private static Index i;
    // Se declara el objeto Gestion (para volver a la pantalla anterior)
    private static Gestion g;

    /**
     * Creates new form Servicios Constructor de la clase Servicios
     */
    public Servicios() throws SQLException {
        initComponents(); // Inicializa los componentes visuales de la interfaz
        // Se crea el objeto Conexion
        cx = new Conexion();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        servicios = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaServicios = new javax.swing.JTable();
        vip = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaVip = new javax.swing.JTable();
        bajoStock = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaStock = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        csvBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 0, 102));

        jTabbedPane1.setBackground(new java.awt.Color(153, 204, 255));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        servicios.setBackground(new java.awt.Color(153, 204, 255));

        tablaServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaServicios.setEnabled(false);
        tablaServicios.setShowHorizontalLines(true);
        tablaServicios.setShowVerticalLines(true);
        jScrollPane4.setViewportView(tablaServicios);

        javax.swing.GroupLayout serviciosLayout = new javax.swing.GroupLayout(servicios);
        servicios.setLayout(serviciosLayout);
        serviciosLayout.setHorizontalGroup(
            serviciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        serviciosLayout.setVerticalGroup(
            serviciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("SERVICIOS MÁS RENTABLES", servicios);

        vip.setBackground(new java.awt.Color(153, 204, 255));

        tablaVip.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaVip.setEnabled(false);
        tablaVip.setShowHorizontalLines(true);
        tablaVip.setShowVerticalLines(true);
        jScrollPane2.setViewportView(tablaVip);

        javax.swing.GroupLayout vipLayout = new javax.swing.GroupLayout(vip);
        vip.setLayout(vipLayout);
        vipLayout.setHorizontalGroup(
            vipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        vipLayout.setVerticalGroup(
            vipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("CLIENTES VIP", vip);

        bajoStock.setBackground(new java.awt.Color(153, 204, 255));

        tablaStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaStock.setEnabled(false);
        tablaStock.setShowHorizontalLines(true);
        tablaStock.setShowVerticalLines(true);
        jScrollPane3.setViewportView(tablaStock);

        javax.swing.GroupLayout bajoStockLayout = new javax.swing.GroupLayout(bajoStock);
        bajoStock.setLayout(bajoStockLayout);
        bajoStockLayout.setHorizontalGroup(
            bajoStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        bajoStockLayout.setVerticalGroup(
            bajoStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("PRODUCTOS CON STOCK BAJO", bajoStock);

        backBtn.setBackground(new java.awt.Color(153, 204, 255));
        backBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz_pelu/imagenes/BACK (1).png"))); // NOI18N
        backBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        homeBtn.setBackground(new java.awt.Color(153, 204, 255));
        homeBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz_pelu/imagenes/home (1).png"))); // NOI18N
        homeBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        csvBtn1.setBackground(new java.awt.Color(153, 204, 255));
        csvBtn1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        csvBtn1.setText("EXPORTAR A CSV");
        csvBtn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        csvBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csvBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(csvBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(csvBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
// Accion que hace el boton de atras
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // Se cierra la pestaña actual
        this.dispose();
        try {
            // Se llama al metodo abrirGestion para abrir la pantalla de gestión
            g.abrirGestion();
        } catch (SQLException ex) {
            // En caso de error de SQL, se registra en el log
            System.getLogger(Datos.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_backBtnActionPerformed
// Accion que hace el boton de home
    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
        // Se cierra la pestaña actual
        this.dispose();
        // Se llama al metodo abrirIndex para abrir la pantalla principal
        i.abrirIndex();
    }//GEN-LAST:event_homeBtnActionPerformed
// Accion que hace el boton de exportar a CSV para servicios, clientes VIP y stock bajo
    private void csvBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csvBtn1ActionPerformed
        try {
            // Se llama al metodo exportarServicios del objeto de conexión para exportar los datos especiales
            cx.exportarServicios();
        } catch (SQLException ex) {
            // En caso de error de SQL, se registra en el log
            System.getLogger(Servicios.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_csvBtn1ActionPerformed

    public void abrirServicios() throws SQLException {
        // Muestra esta pestaña
        this.setVisible(true);
        // Se crea el objeto Index
        i = new Index();
        // Se crea el objeto Gestion
        g = new Gestion();

        // Se llama a los metodos para cargar los datos en cada una de las tablas
        datosServicios();
        datosClientesVip();
        datosStockBajo();

    }

    // Metodo que obtiene y muestra los datos de servicios más rentables
    public void datosServicios() throws SQLException {
        //Crea un arrays con los nombres de las columnas de la tabla
        String[] nombresColumnas = {"ID Servicio", "Nombre", "Precio", "Duracion", "Requiere producto", "Id Peluquera"};

        //Copia el arrays que devuelve la funcion ServiciosRentables de la clase cx en un arrays
        List<Object[]> datosServicios = cx.ServiciosRentables();

        //Crea un arrays multidimensional con las filas del array copiado y las columnas dadas en nombresColumnas
        Object[][] datosArray = new Object[datosServicios.size()][nombresColumnas.length];

        //Bucle para rellenar el arrays datosArray
        for (int i = 0; i < datosServicios.size(); i++) {
            datosArray[i] = datosServicios.get(i);
        }

        //Crea el modelo de tabla cogiendo los datos de los arrays
        DefaultTableModel modelo = new DefaultTableModel(datosArray, nombresColumnas);

        //Hace que la tablaServicios tenga el modelo propuesto antes
        tablaServicios.setModel(modelo);

        //Hace que la tabla haga un autoresize dependiendo del tamaño del arrays
        tablaServicios.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
    }

    // Metodo que obtiene y muestra los datos de clientes VIP
    public void datosClientesVip() throws SQLException {
        //Crea un arrays con los nombres de las columnas de la tabla
        String[] nombresColumnas = {"ID Cliente", "Nombre", "Apellido", "VIP", "Fecha de alta"};

        //Copia el arrays que devuelve la funcion ClientesVip de la clase cx en un arrays
        List<Object[]> datosClientes = cx.ClientesVip();

        //Crea un arrays multidimensional con las filas del array copiado y las columnas dadas en nombresColumnas
        Object[][] datosArray = new Object[datosClientes.size()][nombresColumnas.length];

        //Bucle para rellenar el arrays datosArray
        for (int i = 0; i < datosClientes.size(); i++) {
            datosArray[i] = datosClientes.get(i);
        }

        //Crea el modelo de tabla cogiendo los datos de los arrays
        DefaultTableModel modelo = new DefaultTableModel(datosArray, nombresColumnas);

        //Hace que la tablaVip tenga el modelo propuesto antes
        tablaVip.setModel(modelo);

        //Hace que la tabla haga un autoresize dependiendo del tamaño del arrays
        tablaVip.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
    }

    // Metodo que obtiene y muestra los datos de productos con stock bajo
    public void datosStockBajo() throws SQLException {
        //Crea un arrays con los nombres de las columnas de la tabla
        String[] nombresColumnas = {"ID Producto", "Nombre", "Stock", "Proveedor", "Stock Máximo"};

        //Copia el arrays que devuelve la funcion StockBajo de la clase cx en un arrays
        List<Object[]> datosStockBajo = cx.StockBajo();

        //Crea un arrays multidimensional con las filas del array copiado y las columnas dadas en nombresColumnas
        Object[][] datosArray = new Object[datosStockBajo.size()][nombresColumnas.length];

        //Bucle para rellenar el arrays datosArray
        for (int i = 0; i < datosStockBajo.size(); i++) {
            datosArray[i] = datosStockBajo.get(i);
        }

        //Crea el modelo de tabla cogiendo los datos de los arrays
        DefaultTableModel modelo = new DefaultTableModel(datosArray, nombresColumnas);

        //Hace que la tablaStock tenga el modelo propuesto antes
        tablaStock.setModel(modelo);

        //Hace que la tabla haga un autoresize dependiendo del tamaño del arrays
        tablaStock.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel bajoStock;
    private javax.swing.JButton csvBtn1;
    private javax.swing.JButton homeBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel servicios;
    private javax.swing.JTable tablaServicios;
    private javax.swing.JTable tablaStock;
    private javax.swing.JTable tablaVip;
    private javax.swing.JPanel vip;
    // End of variables declaration//GEN-END:variables
}
