/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz_pelu;

/**
 *
 * @author Carlos
 */
public class gestion extends javax.swing.JFrame {

    //private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(gestion.class.getName());
    private static datos d;
    private static consultas c;

    /**
     * Creates new form gestion
     */
    public gestion() {
        System.out.println("Se inicia el objeto gestion");

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        consultas_Btn = new javax.swing.JButton();
        servicios_Btn = new javax.swing.JButton();
        sincro_Btn = new javax.swing.JButton();
        datos_Btn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        volver = new javax.swing.JMenu();
        simu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 0, 102));

        consultas_Btn.setBackground(new java.awt.Color(153, 204, 255));
        consultas_Btn.setFont(new java.awt.Font("Segoe UI Black", 2, 36)); // NOI18N
        consultas_Btn.setText("C O N S U L T A S");
        consultas_Btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        consultas_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultas_BtnActionPerformed(evt);
            }
        });

        servicios_Btn.setBackground(new java.awt.Color(153, 204, 255));
        servicios_Btn.setFont(new java.awt.Font("Segoe UI Black", 2, 36)); // NOI18N
        servicios_Btn.setText("S E R V I C I O S");
        servicios_Btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        servicios_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicios_BtnActionPerformed(evt);
            }
        });

        sincro_Btn.setBackground(new java.awt.Color(153, 204, 255));
        sincro_Btn.setFont(new java.awt.Font("Segoe UI Black", 2, 36)); // NOI18N
        sincro_Btn.setText("S I N C R O N I Z A R");
        sincro_Btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sincro_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sincro_BtnActionPerformed(evt);
            }
        });

        datos_Btn.setBackground(new java.awt.Color(153, 204, 255));
        datos_Btn.setFont(new java.awt.Font("Segoe UI Black", 2, 36)); // NOI18N
        datos_Btn.setText("D A T O S");
        datos_Btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        datos_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datos_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datos_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(servicios_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sincro_Btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultas_Btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datos_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultas_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(servicios_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sincro_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );

        volver.setText("Volver");
        jMenuBar1.add(volver);

        simu.setText("Simulación");
        jMenuBar1.add(simu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void consultas_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultas_BtnActionPerformed
        // TODO add your handling code here:
        System.out.println("funciona el boton consultas");
        this.dispose();
        c.abrirConsultas();
    }//GEN-LAST:event_consultas_BtnActionPerformed

    private void servicios_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicios_BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_servicios_BtnActionPerformed

    private void sincro_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sincro_BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sincro_BtnActionPerformed

    private void datos_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datos_BtnActionPerformed
        // TODO add your handling code here:
        System.out.println("funciona el boton datos");
        this.dispose();
        d.abrirDatos();
    }//GEN-LAST:event_datos_BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public void abrirGestion() {
        //java.awt.EventQueue.invokeLater(() -> new gestion().setVisible(true));
        this.setVisible(true);
        System.out.println("se crea el objeto datos");
        d = new datos();
        c = new consultas();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultas_Btn;
    private javax.swing.JButton datos_Btn;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton servicios_Btn;
    private javax.swing.JMenu simu;
    private javax.swing.JButton sincro_Btn;
    private javax.swing.JMenu volver;
    // End of variables declaration//GEN-END:variables
}
