/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz_pelu;

import java.sql.SQLException;

/**
 *
 * @author Carlos
 */
public class Index extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Index.class.getName());
    //Se declara el objeto Gestion
    private static Gestion g;
    //Se declara el objeto Simulacion
    private static Simulacion s;
    //Se declara el objeto Login
    private static Login l;
    //Se declara el objeto PupupGest
    private static PopupGest p;
    //Se declara el objeto Conexion
    private static Conexion cx;
    
    /**
     * Creates new form Index
     */
    public Index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        gest_Btn = new javax.swing.JButton();
        sim_Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 0, 102));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz_pelu/imagenes/pelu2.png"))); // NOI18N

        gest_Btn.setBackground(new java.awt.Color(153, 204, 255));
        gest_Btn.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        gest_Btn.setText("G E S T I Ó N");
        gest_Btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gest_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gest_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gest_BtnActionPerformed(evt);
            }
        });

        sim_Btn.setBackground(new java.awt.Color(153, 204, 255));
        sim_Btn.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        sim_Btn.setText("S I M U L A C I Ó N");
        sim_Btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sim_Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sim_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sim_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(gest_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 308, Short.MAX_VALUE)
                .addComponent(sim_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gest_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sim_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(139, 139, 139))
        );

        gest_Btn.getAccessibleContext().setAccessibleName("gest_Btn");
        sim_Btn.getAccessibleContext().setAccessibleName("sim_Btn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //Accion que hace el boton de simulacion
    private void sim_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sim_BtnActionPerformed
        // TODO add your handling code here:
        System.out.println("Funciona el boton simulacion");
        //Se cierra la pestaña actual
        this.dispose();
        //Se llama al metodo abrirSimulacion para abrir la pantalla de simulacion
        s.abrirSimulacion();
    }//GEN-LAST:event_sim_BtnActionPerformed
    //Accion que hace el boton de gestion
    private void gest_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gest_BtnActionPerformed
        //En caso de que sea administrador ejecutará lo siguiente
        if (l.getLog() == 0) {
            System.out.println("Funciona el boton gestion");
            //Se cierra la pestaña actual
            this.dispose();
            try {
                //Se llama al metodo abrirGestion para abrir la pantalla de gestion
                g.abrirGestion();
            } catch (SQLException ex) {
                System.getLogger(Index.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
            //Si es empleado hará lo siguiente
        } else {
            //Se llama al metodo abrirPopup para abrir el Pop up
            p.abrirPopup();
        }

    }//GEN-LAST:event_gest_BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    //Metodo main donde se inicia el programa
    public static void main(String args[]) throws SQLException{
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        System.out.println("Se inicia el programa");
        //Se crea el objeto gestion
        System.out.println("Creamos el objeto gestion");
        g = new Gestion();
        //Se crea el objeto Simulacion
        System.out.println("creamos el objeto simulacion");
        s = new Simulacion();
        //Se crea el objeto Login
        System.out.println("Creamos el objeto login");
        l = new Login();
        //Se llama al metodo abrirLogin para abrir la pantalla de Login
        l.abrirLogin();
        //Se crea el objeto PopUp
        System.out.println("Creamos el objeto Popup");
        p = new PopupGest();
        //Se crea el objeto Conexion
        System.out.println("Creamos el objeto conexion");
        cx = new Conexion();
        //cx.Clientes();
        
    }
    //Metodo que abre el index
    public void abrirIndex() {
        System.out.println(l.getLog());
        //abre esta pestaña
        java.awt.EventQueue.invokeLater(() -> new Index().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gest_Btn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton sim_Btn;
    // End of variables declaration//GEN-END:variables
}
