/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz_pelu;

import java.sql.SQLException;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alumno
 */
public class Servicios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Servicios.class.getName());
    private static Conexion cx;
    private static Index i;
    private static Gestion g;
    /**
     * Creates new form Servicios
     */
    public Servicios() throws SQLException {
        initComponents();
        cx=new Conexion();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        servicios = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaServicios = new javax.swing.JTable();
        vip = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaVip = new javax.swing.JTable();
        bajoStock = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaStock = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 0, 102));

        jTabbedPane1.setBackground(new java.awt.Color(153, 204, 255));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        servicios.setBackground(new java.awt.Color(153, 204, 255));

        tablaServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaServicios.setEnabled(false);
        tablaServicios.setShowHorizontalLines(true);
        tablaServicios.setShowVerticalLines(true);
        jScrollPane4.setViewportView(tablaServicios);

        javax.swing.GroupLayout serviciosLayout = new javax.swing.GroupLayout(servicios);
        servicios.setLayout(serviciosLayout);
        serviciosLayout.setHorizontalGroup(
            serviciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        serviciosLayout.setVerticalGroup(
            serviciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("SERVICIOS MÁS RENTABLES", servicios);

        vip.setBackground(new java.awt.Color(153, 204, 255));

        tablaVip.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaVip.setEnabled(false);
        tablaVip.setShowHorizontalLines(true);
        tablaVip.setShowVerticalLines(true);
        jScrollPane2.setViewportView(tablaVip);

        javax.swing.GroupLayout vipLayout = new javax.swing.GroupLayout(vip);
        vip.setLayout(vipLayout);
        vipLayout.setHorizontalGroup(
            vipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        vipLayout.setVerticalGroup(
            vipLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("CLIENTES VIP", vip);

        bajoStock.setBackground(new java.awt.Color(153, 204, 255));

        tablaStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaStock.setEnabled(false);
        tablaStock.setShowHorizontalLines(true);
        tablaStock.setShowVerticalLines(true);
        jScrollPane3.setViewportView(tablaStock);

        javax.swing.GroupLayout bajoStockLayout = new javax.swing.GroupLayout(bajoStock);
        bajoStock.setLayout(bajoStockLayout);
        bajoStockLayout.setHorizontalGroup(
            bajoStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        bajoStockLayout.setVerticalGroup(
            bajoStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("PRODUCTOS CON STOCK BAJO", bajoStock);

        backBtn.setBackground(new java.awt.Color(153, 204, 255));
        backBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz_pelu/imagenes/BACK (1).png"))); // NOI18N
        backBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        homeBtn.setBackground(new java.awt.Color(153, 204, 255));
        homeBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz_pelu/imagenes/home (1).png"))); // NOI18N
        homeBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
        try {
            g.abrirGestion();
        } catch (SQLException ex) {
            System.getLogger(Datos.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_backBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        i.abrirIndex();
    }//GEN-LAST:event_homeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void abrirServicios() throws SQLException {
        //java.awt.EventQueue.invokeLater(() -> new datos().setVisible(true));
        this.setVisible(true);
        i = new Index();
        g = new Gestion();
        datosServicios();
        datosClientesVip();
        datosStockBajo();
        
    }
    public void datosServicios() throws SQLException {
        String[] nombresColumnas = {"ID Servicio", "Nombre", "Precio", "Duracion", "Requiere producto", "Id Peluquera"};
        List<Object[]> datosServicios = cx.ServiciosRentables();
        Object[][] datosArray = new Object[datosServicios.size()][nombresColumnas.length];
        for (int i = 0; i < datosServicios.size(); i++) {
            datosArray[i] = datosServicios.get(i);
        }
        DefaultTableModel modelo = new DefaultTableModel(datosArray, nombresColumnas);
        tablaServicios.setModel(modelo);
        tablaServicios.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
    }
    public void datosClientesVip() throws SQLException {
        String[] nombresColumnas = {"ID Cliente", "Nombre", "Apellido", "Nº Visitas", "VIP", "Fecha de alta"};
        List<Object[]> datosClientes = cx.ClientesVip();
        Object[][] datosArray = new Object[datosClientes.size()][nombresColumnas.length];
        for (int i = 0; i < datosClientes.size(); i++) {
            datosArray[i] = datosClientes.get(i);
        }
        DefaultTableModel modelo = new DefaultTableModel(datosArray, nombresColumnas);
        tablaVip.setModel(modelo);
        tablaVip.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
    }
    public void datosStockBajo() throws SQLException {
        String[] nombresColumnas = {"ID Producto", "Nombre", "Stock", "Proveedor", "Stock Máximo"};
        List<Object[]> datosStockBajo = cx.StockBajo();
        Object[][] datosArray = new Object[datosStockBajo.size()][nombresColumnas.length];
        for (int i = 0; i < datosStockBajo.size(); i++) {
            datosArray[i] = datosStockBajo.get(i);
        }
        DefaultTableModel modelo = new DefaultTableModel(datosArray, nombresColumnas);
        tablaStock.setModel(modelo);
        tablaStock.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel bajoStock;
    private javax.swing.JButton homeBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel servicios;
    private javax.swing.JTable tablaServicios;
    private javax.swing.JTable tablaStock;
    private javax.swing.JTable tablaVip;
    private javax.swing.JPanel vip;
    // End of variables declaration//GEN-END:variables
}
