/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz_pelu;

/**
 *
 * @author Carlos
 */
public class simulacion extends javax.swing.JFrame {
    
    //private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(simulacion.class.getName());

    /**
     * Creates new form simulacion
     */
    public simulacion() {
        System.out.println("Se inicia el objeto simulacion");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        corteIcon = new javax.swing.JLabel();
        tinteIcon = new javax.swing.JLabel();
        peinadoIcon = new javax.swing.JLabel();
        lavadoIcon = new javax.swing.JLabel();
        peluCorta = new javax.swing.JLabel();
        peluLava = new javax.swing.JLabel();
        peluPeina = new javax.swing.JLabel();
        cleinteLava = new javax.swing.JLabel();
        peluTinte = new javax.swing.JLabel();
        clienteCorte = new javax.swing.JLabel();
        clienteTinte = new javax.swing.JLabel();
        clientePeina = new javax.swing.JLabel();
        corteBarra = new javax.swing.JProgressBar();
        lavadoBarra = new javax.swing.JProgressBar();
        tinteBarra = new javax.swing.JProgressBar();
        peineBarra = new javax.swing.JProgressBar();
        inicio_Btn = new javax.swing.JButton();
        fin_Btn = new javax.swing.JButton();
        pausa_Btn = new javax.swing.JToggleButton();
        clientesAten = new javax.swing.JLabel();
        clientesPen = new javax.swing.JLabel();
        peluAct = new javax.swing.JLabel();
        peluDes = new javax.swing.JLabel();
        numAten = new javax.swing.JLabel();
        numAct = new javax.swing.JLabel();
        numDes = new javax.swing.JLabel();
        numPen = new javax.swing.JLabel();
        menuSim = new javax.swing.JMenuBar();
        volverSim = new javax.swing.JMenu();
        gestSim = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setBackground(new java.awt.Color(204, 0, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 1600));

        corteIcon.setBackground(new java.awt.Color(153, 204, 255));
        corteIcon.setForeground(new java.awt.Color(153, 204, 255));
        corteIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz_pelu/imagenes/corte.png"))); // NOI18N
        corteIcon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255), 5));

        tinteIcon.setBackground(new java.awt.Color(153, 204, 255));
        tinteIcon.setForeground(new java.awt.Color(153, 204, 255));
        tinteIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz_pelu/imagenes/tinte.png"))); // NOI18N
        tinteIcon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255), 5));

        peinadoIcon.setBackground(new java.awt.Color(153, 204, 255));
        peinadoIcon.setForeground(new java.awt.Color(153, 204, 255));
        peinadoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz_pelu/imagenes/peinado.png"))); // NOI18N
        peinadoIcon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255), 5));

        lavadoIcon.setBackground(new java.awt.Color(153, 204, 255));
        lavadoIcon.setForeground(new java.awt.Color(153, 204, 255));
        lavadoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz_pelu/imagenes/lavado.png"))); // NOI18N
        lavadoIcon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255), 5));

        peluCorta.setBackground(new java.awt.Color(51, 255, 255));
        peluCorta.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        peluCorta.setText("PELUQUERA");

        peluLava.setBackground(new java.awt.Color(51, 255, 255));
        peluLava.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        peluLava.setText("PELUQUERA");

        peluPeina.setBackground(new java.awt.Color(51, 255, 255));
        peluPeina.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        peluPeina.setText("PELUQUERA");

        cleinteLava.setBackground(new java.awt.Color(51, 255, 255));
        cleinteLava.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        cleinteLava.setText("CLIENTE");

        peluTinte.setBackground(new java.awt.Color(51, 255, 255));
        peluTinte.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        peluTinte.setText("PELUQUERA");

        clienteCorte.setBackground(new java.awt.Color(51, 255, 255));
        clienteCorte.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        clienteCorte.setText("CLIENTE");

        clienteTinte.setBackground(new java.awt.Color(51, 255, 255));
        clienteTinte.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        clienteTinte.setText("CLIENTE");

        clientePeina.setBackground(new java.awt.Color(51, 255, 255));
        clientePeina.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        clientePeina.setText("CLIENTE");

        inicio_Btn.setBackground(new java.awt.Color(153, 204, 255));
        inicio_Btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        inicio_Btn.setText("INICIAR");
        inicio_Btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        inicio_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicio_BtnActionPerformed(evt);
            }
        });

        fin_Btn.setBackground(new java.awt.Color(153, 204, 255));
        fin_Btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fin_Btn.setText("FINALIZAR");
        fin_Btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fin_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fin_BtnActionPerformed(evt);
            }
        });

        pausa_Btn.setBackground(new java.awt.Color(153, 204, 255));
        pausa_Btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pausa_Btn.setText("PAUSAR / REINICIAR");
        pausa_Btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pausa_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pausa_BtnActionPerformed(evt);
            }
        });

        clientesAten.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        clientesAten.setText("CLIENTES ATENDIDOS:");

        clientesPen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        clientesPen.setText("CLIENTES PENDIENTES: ");

        peluAct.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        peluAct.setText("PELUQUERAS ACTIVAS:");

        peluDes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        peluDes.setText("PELUQUERAS DESCANSANDO:");

        numAten.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        numAten.setText("X");

        numAct.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        numAct.setText("X");

        numDes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        numDes.setText("X");

        numPen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        numPen.setText("X");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cleinteLava, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(peluCorta, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clienteCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(66, 66, 66))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lavadoIcon)
                                    .addGap(66, 66, 66)
                                    .addComponent(corteIcon)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(peluLava, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(250, 250, 250))))
                        .addComponent(peluTinte, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addGap(76, 76, 76))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lavadoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(corteBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tinteBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clienteTinte, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tinteIcon)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(inicio_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(pausa_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(fin_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(peluPeina, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(peineBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(peinadoIcon)
                    .addComponent(clientePeina, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(peluAct)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numAct))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(clientesAten)
                        .addGap(18, 18, 18)
                        .addComponent(numAten)))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(peluDes)
                    .addComponent(clientesPen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numPen)
                    .addComponent(numDes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientesAten)
                    .addComponent(clientesPen)
                    .addComponent(numAten)
                    .addComponent(numPen))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peluAct)
                    .addComponent(peluDes)
                    .addComponent(numAct)
                    .addComponent(numDes))
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peluCorta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(peluLava, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(peluPeina, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(peluTinte, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lavadoIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(corteIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(peinadoIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tinteIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cleinteLava, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clienteCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clienteTinte, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(clientePeina, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lavadoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(corteBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tinteBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(peineBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fin_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inicio_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pausa_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1076, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        volverSim.setText("Volver");
        menuSim.add(volverSim);

        gestSim.setText("Gestión");
        menuSim.add(gestSim);

        setJMenuBar(menuSim);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pausa_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausa_BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pausa_BtnActionPerformed

    private void fin_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fin_BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fin_BtnActionPerformed

    private void inicio_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicio_BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inicio_BtnActionPerformed

   
    public void abrirSimulacion(){
        //java.awt.EventQueue.invokeLater(() -> new simulacion().setVisible(true));
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cleinteLava;
    private javax.swing.JLabel clienteCorte;
    private javax.swing.JLabel clientePeina;
    private javax.swing.JLabel clienteTinte;
    private javax.swing.JLabel clientesAten;
    private javax.swing.JLabel clientesPen;
    private javax.swing.JProgressBar corteBarra;
    private javax.swing.JLabel corteIcon;
    private javax.swing.JButton fin_Btn;
    private javax.swing.JMenu gestSim;
    private javax.swing.JButton inicio_Btn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JProgressBar lavadoBarra;
    private javax.swing.JLabel lavadoIcon;
    private javax.swing.JMenuBar menuSim;
    private javax.swing.JLabel numAct;
    private javax.swing.JLabel numAten;
    private javax.swing.JLabel numDes;
    private javax.swing.JLabel numPen;
    private javax.swing.JToggleButton pausa_Btn;
    private javax.swing.JLabel peinadoIcon;
    private javax.swing.JProgressBar peineBarra;
    private javax.swing.JLabel peluAct;
    private javax.swing.JLabel peluCorta;
    private javax.swing.JLabel peluDes;
    private javax.swing.JLabel peluLava;
    private javax.swing.JLabel peluPeina;
    private javax.swing.JLabel peluTinte;
    private javax.swing.JProgressBar tinteBarra;
    private javax.swing.JLabel tinteIcon;
    private javax.swing.JMenu volverSim;
    // End of variables declaration//GEN-END:variables
}
